import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_BASE_URL ?? "https://ai-unit-test-generator.vercel.app"
  ),
  title: "TestGen·AI – AI unit test generator",
  description:
    "Paste your code and get instant unit tests generated by AI. Supports JS/TS (Jest), Python (pytest), Go, and Rust. Free to try. Bring your own API key.",
  keywords: [
    "unit test generator",
    "ai unit tests",
    "automated testing",
    "jest test generator",
    "pytest generator",
    "test automation",
  ],
  openGraph: {
    title: "TestGen·AI – AI unit test generator",
    description:
      "Paste code, get production-ready unit tests in seconds. Supports Jest, pytest, Go, Rust. Powered by Claude AI.",
    type: "website",
    url: "/",
    siteName: "TestGen·AI",
  },
  twitter: {
    card: "summary_large_image",
    title: "TestGen·AI – AI unit test generator",
    description:
      "Paste code, get production-ready unit tests in seconds. Supports Jest, pytest, Go, Rust. Powered by Claude AI.",
  },
  alternates: {
    canonical: "/",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "SoftwareApplication",
              name: "TestGen·AI",
              description:
                "AI unit test generator. Paste any function or module and get complete, runnable tests in seconds.",
              applicationCategory: "DeveloperApplication",
              operatingSystem: "Web Browser",
              offers: {
                "@type": "Offer",
                price: "0",
                priceCurrency: "USD",
              },
              featureList: [
                "JavaScript/TypeScript (Jest) test generation",
                "Python (pytest) test generation",
                "Go test generation",
                "Rust test generation",
                "Edge case coverage",
              ],
            }),
          }}
        />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
