import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "TestGen·AI – AI unit test generator",
  description:
    "Paste your code and get instant unit tests generated by AI. Supports JS/TS, Python, Go, and Rust. Free to try. Bring your own API key.",
  openGraph: {
    title: "TestGen·AI – AI unit test generator",
    description:
      "Paste code, get production-ready unit tests in seconds. Powered by Claude AI.",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">{children}</body>
    </html>
  );
}
